- name: Configure macOS defaults
  block:
    - name: Enable browsing all network interfaces
      community.general.osx_defaults:
        domain: com.apple.NetworkBrowser
        key: BrowseAllInterfaces
        type: bool
        value: true

    - name: Disable creation of .DS_Store files on network shares
      community.general.osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true

    - name: Disable most recently used apps on dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: false

    - name: Disable automatic window animations
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticWindowAnimationsEnabled
        type: bool
        value: false

    - name: Enable keyrepeat
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: keyrepeat
        type: int
        value: 1

    - name: Disable press and hold
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: ApplePressAndHoldEnabled
        type: bool
        value: false

    - name: Disable automatic spelling correction
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: NSAutomaticSpellingCorrectionEnabled
        type: bool
        value: false

    - name: Show file extensions
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true

    - name: Save screenshots on Pictures folder
      community.general.osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "{{ ansible_env.HOME }}/Pictures"
